import Polychromatic.Colouring
import Polychromatic.PolychromNumber
import Polychromatic.ForMathlib.Misc
import Mathlib.Algebra.Ring.AddAut

/-!
# Block colouring infrastructure and Table 1

This file provides the foundations used by both Case 1 and Case 2 of the
polychromatic colouring theorem for 4-element sets.

## Contents

- **Preliminaries**: the normalized set `zmod_set m a b = {0, b-a, b, 2b-a}`
  in $\mathbb{Z}_m$, and its symmetry under swapping $b$ and $b{-}a$.
- **`BlockColorInfra`**: general tool (`blockColor_polychrom`) for proving
  polychromaticity of cyclic colourings formed by concatenating two block sizes.
- **`Table1`**: concrete block colourings for six specific 4-element sets
  (paper §4, Table 1).
- **`isUnit_intCast_of_natAbs_coprime`**: shared utility used by both
  `Combi.CaseOne` and `Combi.CaseTwo`.

The case analysis itself lives in `Combi.CaseOne` (§4.1) and `Combi.CaseTwo`
(§4.2), with the final assembly in `Combi.lean`.
-/

open Finset Pointwise

/-! ## Preliminaries: the normalized set in ZMod m -/

/--
A helper to define the transformed set in ZMod m.
Corresponds to S = {0, b-a, b, 2b-a} in the informal text.
-/
def zmod_set (m : ℕ) (a b : ℤ) : Finset (ZMod m) :=
  ({0, b - a, b, 2 * b - a} : Finset ℤ).image Int.cast

/-- Auxiliary: the polychromatic number is invariant under the translation that
    maps `{0, a, b, c}` to `zmod_set m a b`. -/
lemma polychromNumber_zmod {a b c : ℤ} {m : ℕ} (hm : m = c - a + b) :
    polychromNumber (({0, a, b, c} : Finset ℤ).image Int.cast : Finset (ZMod m)) =
      polychromNumber (zmod_set m a b) := by
  set S₁ : Finset (ZMod m) := ({0, a, b, c} : Finset ℤ).image Int.cast
  have : zmod_set m a b = (Int.cast (b - a) : ZMod m) +ᵥ S₁ := by
    simp only [image_insert, Int.cast_zero, Int.cast_sub, image_singleton, Int.cast_mul,
      Int.cast_ofNat, vadd_finset_insert, vadd_eq_add, add_zero, sub_add_cancel,
      vadd_finset_singleton, S₁, zmod_set]
    have : (b : ZMod m) - a + c = 0 := by calc
        (b : ZMod m) - a + c = c - a + b := by ring
        _ = ↑(c - a + b : ℤ) := by simp
        _ = (m : ℤ) := by rw [hm]
        _ = 0 := by simp
    grind [sub_add_eq_add_sub, two_mul]
  rw [this, polychromNumber_vadd]

/-- The set {0, b-a, b, 2b-a} is symmetric in the two repeated differences b and b-a:
    swapping them (replacing a by -a, b by b-a) gives the same set. -/
lemma zmod_set_swap (m : ℕ) (a b : ℤ) : zmod_set m (-a) (b - a) = zmod_set m a b := by
  grind [zmod_set]

/-! ## Block coloring infrastructure

Given blocks A (length r) and B (length r+1), concatenate h copies of A followed
by k copies of B to color ℤ_m where m = r·h + (r+1)·k. Polychromaticity reduces
to checking 4 block-pair boundaries (AA, AB, BA, BB), which is decidable for
concrete blocks. The key result is `blockColor_polychrom` at the end of this section.

The remaining lemmas in this section are technical plumbing.
-/

section BlockColorInfra

/--
Check that every starting position in the list `L` hits all three colors {0, 1, 2}
when considering the provided `offsets`.
This is a "linear" check because it doesn't account for cyclic wrap-around;
that is handled by checking all possible block-pair concatenations.
-/
def checkLinearPolychrom (offsets : List ℕ) (L : List (Fin 3)) : Bool :=
  let maxOff := offsets.foldr max 0
  (List.range (L.length - maxOff)).all fun i => ([0, 1, 2] : List (Fin 3)).all fun c =>
      offsets.any fun s => L[i + s]? == some c

/--
Verifies that the block-based coloring remains polychromatic across all possible
transitions between blocks `A` and `B`.
Specifically, it checks the four possible concatenations: AA, AB, BA, and BB.
If these four "local" checks pass, then any sequence of these blocks will
produce a polychromatic coloring.
-/
def checkBlockPairs (offsets : List ℕ) (A B : List (Fin 3)) : Bool :=
  checkLinearPolychrom offsets (A ++ A) &&
  checkLinearPolychrom offsets (A ++ B) &&
  checkLinearPolychrom offsets (B ++ A) &&
  checkLinearPolychrom offsets (B ++ B)

/--
The coloring function generated by concatenating `h` copies of block `A`
followed by some copies of block `B`.
The resulting pattern colors $\mathbb{Z}_m$ where $m = h|A| + k|B|$.
-/
def blockColorVal (A B : List (Fin 3)) (h : ℕ) (p : ℕ) : Fin 3 :=
  if p < A.length * h then (A[p % A.length]?).getD 0
  else (B[(p - A.length * h) % B.length]?).getD 0

private lemma checkLinearPolychrom_spec {offsets : List ℕ} {L : List (Fin 3)}
    (hcheck : checkLinearPolychrom offsets L = true)
    {i : ℕ} (hi : i + offsets.foldr max 0 < L.length) (c : Fin 3) :
    ∃ s ∈ offsets, L[i + s]? = some c := by
  simp only [checkLinearPolychrom, List.all_eq_true, List.mem_range, List.any_eq_true,
    beq_iff_eq] at hcheck
  exact hcheck i (by omega) c (by grind)

/-- Frobenius representation for consecutive block sizes r, r+1:
    any m ≥ r(r-1) can be written as r·h + (r+1)·k. -/
private lemma frobenius_consec {rA m : ℕ} (hrA : 1 < rA) (hm : m ≥ rA * (rA - 1)) :
    ∃ h k, rA * h + (rA + 1) * k = m ∧ 0 < h + k := by
  obtain ⟨a, b, hab⟩ := Nat.exists_add_mul_eq_of_gcd_dvd_of_mul_pred_le rA (rA + 1) m
    (by rw [(Nat.coprime_self_add_right.mpr (Nat.coprime_one_right _)).gcd_eq_one]; exact one_dvd _)
    (by grind [Nat.pred_eq_sub_one, mul_comm rA (rA - 1)])
  refine ⟨a, b, by grind [mul_comm a rA, mul_comm b (rA + 1)], ?_⟩
  by_contra hle; push_neg at hle
  have ha0 : a = 0 := by omega
  have hb0 : b = 0 := by omega
  subst ha0; subst hb0; simp only [zero_mul, zero_add] at hab; subst hab
  have : 0 < rA * (rA - 1) := Nat.mul_pos (by omega) (by omega)
  omega

/-- Bridge: a cyclic coloring function yields HasPolychromColouring. -/
private lemma hasPolychromColouring_of_cyclic {m : ℕ} [NeZero m] [Fact (1 < m)]
    (c : ℕ → Fin 3) (S : Finset (ZMod m))
    (hpoly : ∀ n : ZMod m, ∀ k : Fin 3, ∃ a ∈ S, c (n + a).val = k) :
    HasPolychromColouring (Fin 3) S :=
  ⟨fun x => c x.val, hpoly⟩

/-- If `i % r + s < r`, then `(i + s) % r = i % r + s`. -/
private lemma add_mod_of_lt {i s r : ℕ} (h : i % r + s < r) : (i + s) % r = i % r + s := by
  have hs : s < r := by omega
  rw [Nat.add_mod, Nat.mod_eq_of_lt hs]
  exact Nat.mod_eq_of_lt h

/-- If `r ≤ i % r + s < 2r`, then `(i + s) % r = i % r + s - r`. -/
private lemma add_mod_sub {i s r : ℕ} (hr : 0 < r) (hge : r ≤ i % r + s)
    (hlt : i % r + s < 2 * r) :
    (i + s) % r = i % r + s - r := by
  have h1 := Nat.mod_add_div i r
  have h2 := Nat.mod_lt i hr
  have key : i + s = (i % r + s - r) + (i / r + 1) * r := by
    grind [Nat.sub_add_cancel hge, mul_comm r (i / r)]
  conv_lhs => rw [key]
  rw [Nat.add_mul_mod_self_right]
  exact Nat.mod_eq_of_lt (by omega)

/-- If `M ≤ n` and `n - M < M`, then `n % M = n - M`. -/
private lemma mod_eq_sub {n M : ℕ} (hge : M ≤ n) (hlt : n - M < M) : n % M = n - M := by
  conv_lhs => rw [← Nat.sub_add_cancel hge]
  rw [Nat.add_mod_right, Nat.mod_eq_of_lt hlt]

/-- If `i < r * n` and `i % r + s < r`, then `i + s < r * n`. -/
private lemma add_lt_of_mod_add_lt {i s r n : ℕ} (hr : 0 < r)
    (hi : i < r * n) (h : i % r + s < r) :
    i + s < r * n := by
  have h1 := Nat.mod_add_div i r
  have h2 := Nat.mod_lt i hr
  have h3 : i / r < n := Nat.div_lt_of_lt_mul hi
  have : i / r + 1 ≤ n := by omega
  grind [Nat.mul_le_mul_left r this]

/-- If `r * (n-1) ≤ i` and `r ≤ i % r + s`, then `r * n ≤ i + s`. -/
private lemma ge_mul_of_mod_add_ge {i s r n : ℕ} (hr : 0 < r) (hn : 0 < n)
    (hi_lo : r * (n - 1) ≤ i) (hge : r ≤ i % r + s) :
    r * n ≤ i + s := by
  have := Nat.mod_add_div i r
  have := Nat.mod_lt i hr
  have : n - 1 ≤ i / r := by
    rw [Nat.le_div_iff_mul_le hr]; grind
  have : n ≤ i / r + 1 := by omega
  grind [Nat.mul_le_mul_left r this]

/-! ### Bridge lemmas

These connect list indexing (`XY[js]?`) to `blockColorVal`: if the list element
equals the appropriate block element, the list element equals the coloring value.
-/

/-- If `XY[js]? = A[idx]?` and `p` is in the A-region with `p % |A| = idx`,
    then `XY[js]? = some (blockColorVal A B h p)`. -/
private lemma bcv_eq_A (A B : List (Fin 3)) (h : ℕ)
    (XY : List (Fin 3)) (js p idx : ℕ)
    (hp : p < A.length * h)
    (hmod : p % A.length = idx) (hidx : idx < A.length)
    (hxy : XY[js]? = A[idx]?) :
    XY[js]? = some (blockColorVal A B h p) := by
  rw [hxy, List.getElem?_eq_getElem hidx]
  simp only [blockColorVal, if_pos hp]
  rw [hmod, List.getElem?_eq_getElem hidx, Option.getD_some]

/-- If `XY[js]? = B[idx]?` and `p` is in the B-region with
    `(p - |A|*h) % |B| = idx`, then `XY[js]? = some (blockColorVal A B h p)`. -/
private lemma bcv_eq_B (A B : List (Fin 3)) (h : ℕ)
    (XY : List (Fin 3)) (js p idx : ℕ)
    (hp : ¬(p < A.length * h))
    (hmod : (p - A.length * h) % B.length = idx) (hidx : idx < B.length)
    (hxy : XY[js]? = B[idx]?) :
    XY[js]? = some (blockColorVal A B h p) := by
  rw [hxy, List.getElem?_eq_getElem hidx]
  simp only [blockColorVal, if_neg hp]
  rw [hmod, List.getElem?_eq_getElem hidx, Option.getD_some]

/-- When `i = j + q` and `j + s ≥ r`, then `i + s - (q + r) = j + s - r`. -/
private lemma sub_add_eq {i j s r q : ℕ} (hge : r ≤ j + s)
    (hi : j + q = i) :
    i + s - (q + r) = j + s - r := by grind

/-- When i is in the last block before boundary `r*h`, and j = i%r: `i + s - r*h = j + s - r`. -/
private lemma sub_region_eq {i s r h : ℕ} (hr : 0 < r)
    (hi_lo : r * (h - 1) ≤ i) (hi_hi : i < r * h)
    (hjs_ge : r ≤ i % r + s) :
    i + s - r * h = i % r + s - r := by
  have hdiv := Nat.mod_add_div i r
  have hle : h - 1 ≤ i / r := by rw [Nat.le_div_iff_mul_le hr]; grind
  have hlt : i / r < h := Nat.div_lt_of_lt_mul (by grind)
  have hh : 1 ≤ h := by omega
  have hQr : r * h = r * (i / r) + r := by grind [Nat.sub_add_cancel]
  grind

/-! ### Common goal type for each case

`CaseGoal A B offsets h m i` asserts that there exists a block pair `XY` and
a starting index `j` in `XY` such that `checkLinearPolychrom` passes and every
offset `s` maps to the correct `blockColorVal` value. Each case lemma below
produces a `CaseGoal`, and the main theorem dispatches to them.
-/

/-- The common proof obligation for each case of `blockColor_polychrom`. -/
private def CaseGoal (A B : List (Fin 3)) (offsets : List ℕ) (h m i : ℕ) : Prop :=
  ∃ (XY : List (Fin 3)) (j : ℕ),
    checkLinearPolychrom offsets XY = true ∧
    j + offsets.foldr max 0 < XY.length ∧
    ∀ s, s ≤ offsets.foldr max 0 → XY[j + s]? = some (blockColorVal A B h ((i + s) % m))

/-! ### Case 1: No wrap, AA interior -/
private lemma case_no_wrap_AA (A B : List (Fin 3)) (offsets : List ℕ)
    (h k m i : ℕ)
    (hA : 0 < A.length)
    (hmaxOff : offsets.foldr max 0 ≤ A.length)
    (hAA : checkLinearPolychrom offsets (A ++ A) = true)
    (hm : A.length * h + B.length * k = m)
    (h_no_wrap : i + offsets.foldr max 0 < m)
    (h_AA : i + offsets.foldr max 0 < A.length * h) :
    CaseGoal A B offsets h m i := by
  set maxOff := offsets.foldr max 0
  set j := i % A.length
  have hj_lt : j < A.length := Nat.mod_lt _ hA
  refine ⟨A ++ A, j, hAA, by grind, fun s hsle => ?_⟩
  rw [Nat.mod_eq_of_lt (by grind)]
  have his_A : i + s < A.length * h := by grind
  by_cases hjs_lt : j + s < A.length
  · exact bcv_eq_A A B h _ _ _ _ his_A
      (add_mod_of_lt hjs_lt) hjs_lt (List.getElem?_append_left hjs_lt)
  · push_neg at hjs_lt
    have hjs_sub : j + s - A.length < A.length := by grind
    have hjs_2r : i % A.length + s < 2 * A.length := by grind
    exact bcv_eq_A A B h _ _ _ _ his_A
      (add_mod_sub hA hjs_lt hjs_2r) hjs_sub
      (by grind)

/-! ### Case 2: No wrap, AB boundary -/
private lemma case_no_wrap_AB (A B : List (Fin 3)) (offsets : List ℕ)
    (h k m i : ℕ)
    (hA : 0 < A.length) (hBlen : B.length = A.length + 1)
    (hmaxOff : offsets.foldr max 0 ≤ A.length)
    (hAB : checkLinearPolychrom offsets (A ++ B) = true)
    (hm : A.length * h + B.length * k = m)
    (h_no_wrap : i + offsets.foldr max 0 < m)
    (hA_region : i < A.length * h)
    (h_cross : A.length * h ≤ i + offsets.foldr max 0) :
    CaseGoal A B offsets h m i := by
  set maxOff := offsets.foldr max 0
  set j := i % A.length
  have hj_lt : j < A.length := Nat.mod_lt _ hA
  have hh_pos : 0 < h := by grind
  have hi_lo : A.length * (h - 1) ≤ i := by grind [Nat.mul_sub]
  refine ⟨A ++ B, j, hAB, by grind, fun s hsle => ?_⟩
  rw [Nat.mod_eq_of_lt (by grind)]
  by_cases hjs_lt : j + s < A.length
  · exact bcv_eq_A A B h _ _ _ _
      (add_lt_of_mod_add_lt hA hA_region hjs_lt)
      (add_mod_of_lt hjs_lt) hjs_lt
      (List.getElem?_append_left hjs_lt)
  · push_neg at hjs_lt
    have hjs_B : j + s - A.length < B.length := by grind
    have his_ge : A.length * h ≤ i + s := ge_mul_of_mod_add_ge hA hh_pos hi_lo hjs_lt
    have hnot_A : ¬(i + s < A.length * h) := by grind
    refine bcv_eq_B A B h _ _ _ _ hnot_A ?_ hjs_B ?_
    · rw [sub_region_eq hA hi_lo hA_region hjs_lt,
        Nat.mod_eq_of_lt (by grind)]
    · grind

/-! ### Case 3: No wrap, BB -/
private lemma case_no_wrap_BB (A B : List (Fin 3)) (offsets : List ℕ)
    (h k m i : ℕ)
    (hBlen : B.length = A.length + 1)
    (hmaxOff : offsets.foldr max 0 ≤ A.length)
    (hBB : checkLinearPolychrom offsets (B ++ B) = true)
    (hm : A.length * h + B.length * k = m)
    (h_no_wrap : i + offsets.foldr max 0 < m)
    (hB_region : A.length * h ≤ i) :
    CaseGoal A B offsets h m i := by
  set maxOff := offsets.foldr max 0
  set j := (i - A.length * h) % B.length
  have hj_lt : j < B.length := Nat.mod_lt _ (by grind)
  refine ⟨B ++ B, j, hBB, by grind, fun s hsle => ?_⟩
  rw [Nat.mod_eq_of_lt (by grind)]
  by_cases hjs_lt : j + s < B.length
  · exact bcv_eq_B A B h _ _ _ _ (by grind)
      (by rw [Nat.sub_add_comm hB_region]; exact add_mod_of_lt hjs_lt)
      hjs_lt (List.getElem?_append_left hjs_lt)
  · push_neg at hjs_lt
    have hjs_sub : j + s - B.length < B.length := by grind
    exact bcv_eq_B A B h _ _ _ _ (by grind)
      (by rw [Nat.sub_add_comm hB_region]; exact add_mod_sub (by grind) hjs_lt (by grind))
      hjs_sub
      (by grind)

/-! ### Case 4: Wrap, A region (k = 0) -/
private lemma case_wrap_A (A B : List (Fin 3)) (offsets : List ℕ)
    (h m i : ℕ)
    (hA : 0 < A.length)
    (hmaxOff : offsets.foldr max 0 ≤ A.length)
    (hAA : checkLinearPolychrom offsets (A ++ A) = true)
    (hm : A.length * h = m)
    (hi : i < m)
    (h_wrap : m ≤ i + offsets.foldr max 0)
    (hA_region : i < A.length * h) :
    CaseGoal A B offsets h m i := by
  set maxOff := offsets.foldr max 0
  subst hm
  set j := i % A.length
  have hj_lt : j < A.length := Nat.mod_lt _ hA
  have hh_pos : 0 < h := by grind
  have hi_lo : A.length * (h - 1) ≤ i := by grind [Nat.mul_sub]
  have hAh : A.length ≤ A.length * h := Nat.le_mul_of_pos_right _ hh_pos
  refine ⟨A ++ A, j, hAA, by grind, fun s hsle => ?_⟩
  by_cases hjs_lt : j + s < A.length
  · have his_lt : i + s < A.length * h := add_lt_of_mod_add_lt hA (by grind) hjs_lt
    rw [Nat.mod_eq_of_lt his_lt]
    exact bcv_eq_A A B h _ _ _ _ his_lt
      (add_mod_of_lt hjs_lt) hjs_lt (List.getElem?_append_left hjs_lt)
  · push_neg at hjs_lt
    have his_ge : A.length * h ≤ i + s := ge_mul_of_mod_add_ge hA hh_pos hi_lo hjs_lt
    have hmod : (i + s) % (A.length * h) = i + s - A.length * h := mod_eq_sub his_ge (by grind)
    have hsub_eq := sub_region_eq hA hi_lo (by grind) hjs_lt
    have hjs_idx : j + s - A.length < A.length := by grind
    refine bcv_eq_A A B h _ _ _ _ (by grind)
      (by rw [hmod, Nat.mod_eq_of_lt (by grind), hsub_eq])
      hjs_idx ?_
    grind

/-! ### Case 5: Wrap, B region, h > 0 → BA -/
private lemma case_wrap_BA (A B : List (Fin 3)) (offsets : List ℕ)
    (h k m i : ℕ)
    (hA : 0 < A.length) (hBlen : B.length = A.length + 1)
    (hmaxOff : offsets.foldr max 0 ≤ A.length)
    (hBA : checkLinearPolychrom offsets (B ++ A) = true)
    (hm : A.length * h + B.length * k = m)
    (hi : i < m)
    (h_wrap : m ≤ i + offsets.foldr max 0)
    (hB_region : A.length * h ≤ i)
    (hh_pos : 0 < h) (hk_pos : 0 < k) :
    CaseGoal A B offsets h m i := by
  set maxOff := offsets.foldr max 0
  have hAh : A.length ≤ A.length * h := Nat.le_mul_of_pos_right _ hh_pos
  have hBk : B.length ≤ B.length * k := Nat.le_mul_of_pos_right _ hk_pos
  set j := (i - A.length * h) % B.length
  have hj_lt : j < B.length := Nat.mod_lt _ (by grind)
  have hi_B : i - A.length * h < B.length * k := by grind
  have hk_lo : B.length * (k - 1) ≤ i - A.length * h := by grind [Nat.mul_sub]
  refine ⟨B ++ A, j, hBA, by grind, fun s hsle => ?_⟩
  by_cases hjs_lt : j + s < B.length
  · -- Still in B
    have his_lt : (i - A.length * h) + s < B.length * k :=
      add_lt_of_mod_add_lt (by grind) hi_B hjs_lt
    rw [Nat.mod_eq_of_lt (by grind)]
    exact bcv_eq_B A B h _ _ _ _ (by grind)
      (by rw [Nat.sub_add_comm hB_region]; exact add_mod_of_lt hjs_lt)
      hjs_lt (List.getElem?_append_left hjs_lt)
  · -- Wrapped to A region
    push_neg at hjs_lt
    have his_ge : m ≤ i + s := by
      have := ge_mul_of_mod_add_ge (by grind) hk_pos hk_lo hjs_lt
      grind
    have hmod : (i + s) % m = i + s - m := mod_eq_sub his_ge (by grind)
    have hsub_eq : i + s - m = j + s - B.length := by
      have := sub_region_eq (by grind) hk_lo hi_B hjs_lt
      grind
    have hjs_idx : j + s - B.length < A.length := by grind
    refine bcv_eq_A A B h _ _ _ _ (by grind)
      (by rw [hmod, Nat.mod_eq_of_lt (by grind), hsub_eq])
      hjs_idx ?_
    grind

/-! ### Case 6: Wrap, B region, h = 0 → BB -/
private lemma case_wrap_BB (A B : List (Fin 3)) (offsets : List ℕ)
    (k m i : ℕ)
    (hBlen : B.length = A.length + 1)
    (hmaxOff : offsets.foldr max 0 ≤ A.length)
    (hBB : checkLinearPolychrom offsets (B ++ B) = true)
    (hm : B.length * k = m)
    (hi : i < m)
    (h_wrap : m ≤ i + offsets.foldr max 0)
    (hk_pos : 0 < k) :
    CaseGoal A B offsets 0 m i := by
  set maxOff := offsets.foldr max 0
  have hBk : B.length ≤ B.length * k := Nat.le_mul_of_pos_right _ hk_pos
  set j := i % B.length
  have hj_lt : j < B.length := Nat.mod_lt _ (by grind)
  have hk_lo : B.length * (k - 1) ≤ i := by grind [Nat.mul_sub]
  refine ⟨B ++ B, j, hBB, by grind, fun s hsle => ?_⟩
  by_cases hjs_lt : j + s < B.length
  · have his_lt : i + s < B.length * k := add_lt_of_mod_add_lt (by grind) (by grind) hjs_lt
    rw [Nat.mod_eq_of_lt (by grind)]
    exact bcv_eq_B A B 0 _ _ _ _
      (by omega)
      (by grind [add_mod_of_lt hjs_lt])
      hjs_lt (List.getElem?_append_left hjs_lt)
  · push_neg at hjs_lt
    have his_ge : m ≤ i + s := by
      have := ge_mul_of_mod_add_ge (by grind) hk_pos hk_lo hjs_lt
      grind
    have hmod : (i + s) % m = i + s - m := mod_eq_sub his_ge (by grind)
    have hsub_eq : i + s - m = j + s - B.length := by
      rw [← hm]
      exact sub_region_eq (by grind) hk_lo (by grind) hjs_lt
    have hjs_idx : j + s - B.length < B.length := by grind
    refine bcv_eq_B A B 0 _ _ _ _
      (by omega)
      (by rw [Nat.mul_zero, Nat.sub_zero, hmod, Nat.mod_eq_of_lt (by grind), hsub_eq])
      hjs_idx ?_
    grind

/-! ### Main result of the block coloring infrastructure -/

/-- **Key infrastructure theorem.** If all block-pair checks pass, the block coloring is
    polychromatic for any m expressible as rA·h + rB·k. This is the main interface
    used by the Table 1 lemmas below. -/
theorem blockColor_polychrom
    (A B : List (Fin 3)) (offsets : List ℕ)
    (hA : 0 < A.length) (hBlen : B.length = A.length + 1)
    (hmaxOff : offsets.foldr max 0 ≤ A.length)
    (hpairs : checkBlockPairs offsets A B = true)
    {h k : ℕ} (hhk : 0 < h + k) {m : ℕ}
    (hm : A.length * h + B.length * k = m)
    {i : ℕ} (hi : i < m) (c : Fin 3) :
    ∃ s ∈ offsets, blockColorVal A B h ((i + s) % m) = c := by
  set maxOff := offsets.foldr max 0
  simp only [checkBlockPairs, Bool.and_eq_true] at hpairs
  obtain ⟨⟨⟨hAA, hAB⟩, hBA⟩, hBB⟩ := hpairs
  -- Reduce to CaseGoal
  suffices hg : CaseGoal A B offsets h m i by
    obtain ⟨XY, j, hXY_check, hj_bound, hcorr⟩ := hg
    obtain ⟨s, hs_mem, hs_eq⟩ := checkLinearPolychrom_spec hXY_check hj_bound c
    refine ⟨s, hs_mem, ?_⟩
    have := hcorr s (List.le_max_of_le' 0 hs_mem le_rfl)
    grind
  -- Dispatch to case lemmas
  by_cases h_wrap : i + maxOff < m
  · by_cases hA_region : i < A.length * h
    · by_cases h_cross : i + maxOff < A.length * h
      · exact case_no_wrap_AA A B offsets h k m i hA hmaxOff hAA hm h_wrap h_cross
      · push_neg at h_cross
        have hk_pos : 0 < k := by grind
        exact case_no_wrap_AB A B offsets h k m i hA hBlen hmaxOff hAB hm h_wrap hA_region h_cross
    · push_neg at hA_region
      exact case_no_wrap_BB A B offsets h k m i hBlen hmaxOff hBB hm h_wrap hA_region
  · push_neg at h_wrap
    by_cases hA_region : i < A.length * h
    · have hk0 : k = 0 := by rw [hBlen] at hm; nlinarith [hmaxOff]
      subst hk0; simp only [mul_zero, add_zero] at hm
      exact case_wrap_A A B offsets h m i hA hmaxOff hAA hm hi h_wrap hA_region
    · push_neg at hA_region
      have hk_pos : 0 < k := by nlinarith [hm, hA_region, hi]
      by_cases hh_pos : 0 < h
      · exact case_wrap_BA A B offsets h k m i hA hBlen hmaxOff
          hBA hm hi h_wrap hA_region hh_pos hk_pos
      · have hh0 : h = 0 := by grind
        subst hh0
        simp only [mul_zero, zero_add] at hm
        exact case_wrap_BB A B offsets k m i hBlen hmaxOff hBB hm hi h_wrap hk_pos

end BlockColorInfra

/-! ## Table 1: Block concatenation colorings (paper §4, Table 1)

Each `table1_*` lemma constructs a concrete 3-polychromatic coloring for a specific
4-element set using `blockColor_polychrom`. These are intermediate results used in
subcases (1a) and (1c) of Case 1.

| Lemma | Set | Block size r | Min m |
|-------|-----|-------------|-------|
| `table1_0123` | {0,1,2,3} | 3 | 6 |
| `table1_0134` | {0,1,3,4} | 6 | 30 |
| `table1_0235` | {0,2,3,5} | 6 | 30 |
| `table1_0347` | {0,3,4,7} | 9 | 72 |
| `table1_0358` | {0,3,5,8} | 9 | 72 |
| `table1_0145` | {0,1,4,5} | 7 | 42 |
-/

section Table1

variable (m : ℕ)

/-- Helper to convert block coloring polychromaticity into HasPolychromColouring
    for a specific finset of offsets in ZMod m. -/
private lemma table1_of_blockColor (A B : List (Fin 3)) (offsets : List ℕ)
    (S : Finset (ZMod m))
    (hA : 2 < A.length) (hBlen : B.length = A.length + 1)
    (hmaxOff : offsets.foldr max 0 ≤ A.length)
    (hpairs : checkBlockPairs offsets A B = true)
    (hm : m ≥ A.length * (A.length - 1))
    (hS : ∀ a : ZMod m, a ∈ S ↔ ∃ s ∈ offsets, (s : ZMod m) = a) :
    HasPolychromColouring (Fin 3) S := by
  have hA_lt_m : A.length < m := by
    have : A.length * 2 ≤ A.length * (A.length - 1) := by gcongr; omega
    omega
  haveI : NeZero m := ⟨by omega⟩
  haveI : Fact (1 < m) := ⟨by omega⟩
  obtain ⟨h, k, hm_eq, hhk⟩ := frobenius_consec (by omega : 1 < A.length) hm
  have hm_eq' : A.length * h + B.length * k = m := by grind
  apply hasPolychromColouring_of_cyclic (blockColorVal A B h) S
  intro n target
  obtain ⟨s, hs_mem, hs_eq⟩ := blockColor_polychrom A B offsets (by omega) hBlen hmaxOff
    hpairs hhk hm_eq' (ZMod.val_lt n) target
  refine ⟨(s : ZMod m), (hS _).mpr ⟨s, hs_mem, rfl⟩, ?_⟩
  have : s < m := lt_of_le_of_lt (le_trans (List.le_max_of_le' 0 hs_mem le_rfl) hmaxOff) hA_lt_m
  rw [ZMod.val_add, ZMod.val_natCast, Nat.mod_eq_of_lt this]
  exact hs_eq

/-- {0,1,2,3}: blocks [0,1,2] (r=3), [0,0,1,2] (r+1=4). Frobenius bound: m ≥ 6. -/
lemma table1_0123 (hm : m ≥ 6) : HasPolychromColouring (Fin 3) ({0, 1, 2, 3} : Finset (ZMod m)) :=
  table1_of_blockColor m [0,1,2] [0,0,1,2] [0,1,2,3]
    {0, 1, 2, 3} (by simp) (by simp) (by decide) (by decide) hm
    (by intro a; simp; tauto)

/-- {0,1,3,4}: blocks [0,0,1,2,1,2] (r=6), [0,0,0,1,2,1,2] (r+1=7). Frobenius: m ≥ 30. -/
lemma table1_0134 (hm : m ≥ 30) : HasPolychromColouring (Fin 3) ({0, 1, 3, 4} : Finset (ZMod m)) :=
  table1_of_blockColor m [0,0,1,2,1,2] [0,0,0,1,2,1,2] [0,1,3,4]
    {0, 1, 3, 4} (by simp) (by simp) (by decide) (by decide) hm
    (by intro a; simp; tauto)

/-- {0,2,3,5}: blocks [0,0,1,1,2,2] (r=6), [0,0,0,1,1,2,2] (r+1=7). Frobenius: m ≥ 30. -/
lemma table1_0235 (hm : m ≥ 30) : HasPolychromColouring (Fin 3) ({0, 2, 3, 5} : Finset (ZMod m)) :=
  table1_of_blockColor m [0,0,1,1,2,2] [0,0,0,1,1,2,2] [0,2,3,5]
    {0, 2, 3, 5} (by simp) (by simp) (by decide) (by decide) hm
    (by intro a; simp; tauto)

/-- {0,3,4,7}: blocks [0,0,0,1,1,1,2,2,2] (r=9), [0,0,0,0,1,1,1,2,2,2] (r+1=10).
    Frobenius: m ≥ 72. -/
lemma table1_0347 (hm : m ≥ 72) : HasPolychromColouring (Fin 3) ({0, 3, 4, 7} : Finset (ZMod m)) :=
  table1_of_blockColor m [0,0,0,1,1,1,2,2,2] [0,0,0,0,1,1,1,2,2,2] [0,3,4,7]
    {0, 3, 4, 7} (by simp) (by simp) (by decide) (by decide) hm
    (by intro a; simp; tauto)

/-- {0,3,5,8}: blocks [0,0,0,1,1,1,2,2,2] (r=9), [0,0,0,0,1,1,1,2,2,2] (r+1=10).
    Frobenius: m ≥ 72. -/
lemma table1_0358 (hm : m ≥ 72) : HasPolychromColouring (Fin 3) ({0, 3, 5, 8} : Finset (ZMod m)) :=
  table1_of_blockColor m [0,0,0,1,1,1,2,2,2] [0,0,0,0,1,1,1,2,2,2] [0,3,5,8]
    {0, 3, 5, 8} (by simp) (by simp) (by decide) (by decide) hm
    (by intro a; simp; tauto)

/-- {0,1,4,5}: blocks [0,0,0,1,2,1,2] (r=7), [0,0,0,0,1,2,1,2] (r+1=8). Frobenius: m ≥ 42. -/
lemma table1_0145 (hm : m ≥ 42) : HasPolychromColouring (Fin 3) ({0, 1, 4, 5} : Finset (ZMod m)) :=
  table1_of_blockColor m [0,0,0,1,2,1,2] [0,0,0,0,1,2,1,2] [0,1,4,5]
    {0, 1, 4, 5} (by simp) (by simp) (by decide) (by decide) hm
    (by intro a; simp; tauto)

end Table1

/-! ## Shared utility lemma -/

lemma isUnit_intCast_of_natAbs_coprime {n : ℕ} {b : ℤ}
    (h : Nat.gcd b.natAbs n = 1) :
    IsUnit (Int.cast b : ZMod n) := by
  have hu : IsUnit (b.natAbs : ZMod n) := (ZMod.isUnit_iff_coprime _ _).mpr h
  rcases Int.natAbs_eq b with hb | hb
  · have : (Int.cast b : ZMod n) = ↑b.natAbs := by rw [hb]; simp
    rwa [this]
  · have : (Int.cast b : ZMod n) = -↑b.natAbs := by rw [hb]; simp
    rw [this]; exact hu.neg
