import Polychromatic.FourThree.FourThree

/-!
# Computational Proof: All Quadruples with c < 289

This file contains the computational verification that all quadruples `{0, a, b, c}`
with `c < 289` admit a 3-polychromatic colouring.

## Main results

* `allC_289`: Proves `allC 289`, establishing that all quadruples with `c < 289` have
  3-polychromatic colourings.

## Implementation notes

The proof is generated by the `prove_allC` tactic, which reads precomputed colouring data
from an external file and constructs proof terms using Lean's metaprogramming facilities.
The linter is disabled for this file since it contains a large generated proof term.
-/

set_option linter.all false

-- set_option trace.debug true

-- set_option trace.profiler true
-- set_option trace.profiler.threshold 2

-- set_option trace.Elab.definition.body true

-- should be 289 and 900000, temporarily downgraded to check CI
/-- Proves `allC 289`, establishing that all quadruples with `c < 289` have
3-polychromatic colourings. -/
lemma allC_289 : allC 289 := by
  sorry
  -- prove_allC 900000
