title: Polychromatic
description: >-
  Polychromatic colourings of integers
baseurl: "/Polychromatic"
url: "https://b-mehta.github.io"
repository: b-mehta/Polychromatic
github_username: b-mehta

collections:
  pages:
    output: true
    permalink: /:path

remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
    values:
      seo_description_max_words: 10

webrick:
  headers:
    Access-Control-Allow-Origin: "*"
