name = "polychromaticSite"
defaultTargets = ["docs"]

[[require]]
name = "subverso"
git = "https://github.com/leanprover/subverso"
rev = "0bd508e8362f56d4a05cbf63614d4c97db954041"

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.31.0"

[[lean_lib]]
name = "Berso"

[[lean_lib]]
name = "PolychromaticSite"

[[lean_exe]]
name = "docs"
root = "PolychromaticMain"
