name = "polychromaticSite"
defaultTargets = ["docs"]

[[require]]
name = "subverso"
git = "https://github.com/leanprover/subverso"
rev = "ce893b9042128037e2d3c0158b9567fab9fae268"

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.30.0"

[[lean_lib]]
name = "Berso"

[[lean_lib]]
name = "PolychromaticSite"

[[lean_exe]]
name = "docs"
root = "PolychromaticMain"
