name = "polychromaticSite"
defaultTargets = ["docs"]

[[require]]
name = "subverso"
git = "https://github.com/leanprover/subverso"
rev = "4539e605ff834c35ecc0bcd0b7daec69163fd9f0"

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "main"

[[lean_lib]]
name = "Berso"

[[lean_lib]]
name = "PolychromaticSite"

[[lean_exe]]
name = "docs"
root = "PolychromaticMain"
