import Polychromatic.Colouring
import Polychromatic.Compactness
import Polychromatic.DiscreteProbability
import Polychromatic.Existence
import Polychromatic.ForMathlib.Misc
import Polychromatic.LocalLemma
import Polychromatic.Main
import Polychromatic.PolychromNumber
